#!/usr/bin/env python

from action import Action
from actor import Actor, KilledActor
from player import Player
from renderer import Renderer
import common

import pygame

def main():
    # Initialize Everything
    pygame.init()
    screen = pygame.display.set_mode((1024, 768))
    pygame.display.set_caption('PCE Test')
    pygame.mouse.set_visible(1)

    # Prepare Game Objects
    clock = pygame.time.Clock()
    render = Renderer(screen)

    # Prepare Scene
    render.set_background(common.load_image('background.jpg'))

    meca = Player(screen,
                  Action('meca_head_left_'),
                  Action('meca_weels_left_'),
                  (0, 10), (100, 100))

    render.add_players('meca1', meca)

    # Main Loop
    while 1:
        clock.tick(20)

        # Handle Input Events
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return
            elif event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                return

        # Draw scene
        render.update()
        pygame.display.flip()


if __name__ == '__main__':
    main()
