CFLAGS=`sdl-config --cflags`
LDFLAGS=`sdl-config --libs`

CFLAGS+=-I./pc -I./common -I./
LDFLAGS+=-L./pc -L./common -L./

CFLAGS+=-DFSTV_LINUX

all: ftve

main.o: pc/main.c
	g++ -c $(CFLAGS) $^

%.o: %.c
	g++ -c $(CFLAGS) $^

ftve: main.o scene.o init.o
	g++ $(LDFLAGS) $^ -o $@

clean:
	$(RM) ftve
	$(RM) *.o pc/*.o common/*.o
	$(RM) *~ pc/*~ common/*~